### ISSUE TITLE
SPIERSview mac

### ISSUE THREAD

**Issue by RussellGarwood** [palaeoware/SPIERS#16]
**Describe the bug**
View actually doesn’t work at all – file processes and loads, but no visible image. It’s possible the machine is too low powered, 

**To Reproduce**
1. Open a file in view on MAC
2. Wait for it to load then it won't appear

**Expected behavior**
Model should appear in graphics view

**Desktop (please complete the following information):**
 - Mac OS

**Comment by RussellGarwood** [comment]
Warnings now fixed - waiting for testing to check whether this has worked (VM still looks blank on model load).

**Comment by alanspencer** [comment]
Posible fix now in place for macOS (Catlina). See commit: 82a045441d31823f6d5ff18dc99cb65dd6cf4a93

**Comment by alanspencer** [comment]
New issue - SPIERSview does not close down correctly on macOS. Icon for program remains after closing app, macOS indicates program still running. Force closing of app only way to remove it (with: Option, Cmd, ESC). Most likley caused by incorrect destruction of new vertex array buffer. To be investigated.

**Comment by alanspencer** [comment]
This should now be solved.
